name: nj-bibel
version: 0.1
description: An online recovery version Bible Node.js application with no database.
keywords:
- bible
- recovery
- nodejs
home: https://access.redhat.com
sources:
- https://github.com/yistLin/nj-bibel
